# Generated by Django 5.1.6 on 2025-02-19 14:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NedajTypeModel',
            fields=[
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('machine_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('machine_name', models.CharField(help_text='Machine name reference', max_length=254)),
                ('machine_code', models.CharField(help_text='Machine code', max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('nedaj_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='taf.nedajtypemodel')),
            ],
            options={
                'db_table': 'Machine',
                'ordering': ['machine_name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('total_liters', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prev_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('sold_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('remaining', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('stocked_date', models.DateTimeField(auto_now_add=True)),
                ('nedaj_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='taf.nedajtypemodel')),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='TafRecordModel',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('new_record', models.DecimalField(decimal_places=3, help_text='New machine record value', max_digits=15)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('record_update', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='taf.machinemodel')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
        migrations.CreateModel(
            name='SalesInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.UUIDField(default=uuid.uuid4)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sold_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sold_in_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_sale', to='taf.machinemodel')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='taf.tafrecordmodel')),
            ],
        ),
    ]
